repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    # Run the linter.
    - id: ruff
      entry: bash -c "cd python && uv run ruff check --force-exclude"
    # Run the formatter.
    - id: ruff-format
      entry: bash -c "cd python && uv run ruff format --force-exclude"
